name: Manual Test Run

run-name: Run ${{ github.event.inputs.test_type }} tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: Select Test Category
        required: true
        type: choice
        options:
          - smoke
          - regression
          - all
        default: "smoke"

jobs:
  call_base:
    uses: ./.github/workflows/playwright-base.yml
    with:
      test_type: ${{ github.event.inputs.test_type }}