name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      checkboxtitle:
        description: Run Smoke Tests
        type: choice
        required: true
        options:
          - regression
          - smoke

jobs:
  run-regression-tests:
    if: github.event.inputs.checkboxtitle == 'regression'
    runs-on: ubuntu-latest
    env:
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      USER_NAME: ${{ secrets.USER_NAME }}
      USER_ID: ${{ secrets.USER_ID }}
      USER_LOCATION: ${{ secrets.USER_LOCATION }}
      HEADLESS: ${{ secrets.HEADLESS }}
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
      BASE_CLIENT_URL: ${{ secrets.BASE_CLIENT_URL }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      API_BASE_USER_URL: ${{ secrets.API_BASE_USER_URL }}

    steps:
      - name: Setup
        run: echo "Clone repo and install node.js"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: |
          echo "Install all dependencies"
          npm ci

      - name: Install Playwright Browsers
        run: |
          echo "Install Playwright browsers"
          npx playwright install --with-deps

      - name: Run regression tests
        run: |
          echo "Run regression tests"
          npm run regression

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright report
          path: playwright-report/
          retention-days: 7       


