name: Playwright Base 

run-name: Base Setup

on: 
  workflow_call:
    inputs:
      test_type:
        type: string
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    env:
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      USER_NAME: ${{ secrets.USER_NAME }}
      USER_ID: ${{ secrets.USER_ID }}
      USER_LOCATION: ${{ secrets.USER_LOCATION }}
      HEADLESS: ${{ secrets.HEADLESS }}
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
      BASE_CLIENT_URL: ${{ secrets.BASE_CLIENT_URL }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      API_BASE_USER_URL: ${{ secrets.API_BASE_USER_URL }}

    steps:
      - name: Setup
        run: echo "Clone repo and install node.js"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install Dependencies
        run: |
          echo "Install all dependencies"
          npm ci

      - name: Install PW Chrome
        run: |
          echo "Install Playwright Chrome Browser"
          npx playwright install chromium --with-deps

      - name: Run Tests
        run: |
          echo "Running - ${{ inputs.test_type }} tests"
          if [ "${{ inputs.test_type }}" == "all" ]; then
            npm run test
          else
            npm run ${{ inputs.test_type }}
          fi

      - name: Upload Artifact        
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright report
          path: playwright-report/
          retention-days: 10     

